---
- name: import the key for the official MongoDB repository
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: "0C49F3730359A14518585931BC711F9BA15703C6"
    state: present 
    
- name: add official MongoDB repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    state: present
    filename: 'mongodb-org-3.4'

- name: update repo list & download MongoDB package
  apt:
    name: mongodb-org
    update_cache: yes

- name: start MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes # enable service to start on boot

# create app DB using ansible
- name: install pip
  apt:
    pkg: python-pip

- name: install pymongo module
  pip:
    name: pymongo

# - name: create app DB
#   mongodb_user:
#     database: '{{ app_name }}'
#     name: '{{ db_user }}'
#     password: '{{ db_pwd }}'
#     state: present #The localhost login exception only allows the first admin account to be created

# end create app DB using ansible

      