---
- name: add php repository to install php7.1
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: update packages
  apt:
    update_cache: yes

- name: install required packages
  action: apt pkg={{ item }} state=installed update_cache=yes state=latest
  with_items:
    - php7.1
    - php7.1-common
    - php7.1-mbstring
    - php7.1-xml
    - php7.1-fpm

- name: secure php cgi
  shell: echo "cgi.fix_pathinfo=0" >> /etc/php/7.1/fpm/php.ini
  notify:
    - restart php7.1-fpm