---

- name: install required packages
  action: apt pkg={{ item }} state=installed update_cache=yes state=latest
  with_items:
    - php7.0
    - php-fpm
    - php7.0-common
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-fpm
    - php7.0-gd
    - php7.0-fpm
    - php-mongodb
    - php7.0-mcrypt
    - unzip

- name: secure php cgi
  shell: echo "cgi.fix_pathinfo=0" >> /etc/php/7.0/fpm/php.ini
  notify:
    - restart php7.0-fpm
